---
# Install Cassandra (Avoiding Docker for now due to stability issues)
- name: Configure Datastax repo
  copy: src=datastax.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: Install Cassandra
  dnf: name=dsc22 enablerepo=datastax state=latest

- name: Start Cassandra
  service: name=cassandra enabled=yes state=started

