---
# Install some stuff I like to have

- name: Install Various Tools
  dnf: name={{item}} state=present
  with_items:
   - gcc
   - make
   - ruby-devel
   - gcc-c++
   - libxml2
   - libxml2-devel
   - libxslt
   - libxslt-devel
   - rubygem-nokogiri
   - findutils
   - git
   - ruby
   - rpm-build
   - htop
   - tig
   - adobe-source-code-pro-fonts
   - perf
   - powertop
   - mc
   - the_silver_searcher

- name: Configure HipChat repo
  copy: src=hipchat.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644
  tags:
    - hipchat

- name: Install HipChat
  dnf: name=hipchat4 enablerepo=hipchat state=latest
  tags:
    - hipchat
