---
# Install some stuff I like to have

- name: Install Various Tools
  dnf: name={{item}} state=present
  with_items:
   - gcc
   - make
   - ruby-devel
   - gcc-c++
   - libxml2
   - libxml2-devel
   - libxslt
   - libxslt-devel
   - rubygem-nokogiri
   - findutils
   - git
   - ruby
   - rpm-build
   - htop
   - tig
   - adobe-source-code-pro-fonts
   - perf
   - powertop
   - mc
   - the_silver_searcher
   - java-9-openjdk
   - java-9-openjdk-devel
   - java-1.8.0-openjdk
   - java-1.8.0-openjdk-devel
   - tuned
   - origin
   - docker
   - powertop
   - eclipse
